language: node_js
node_js:
  - "6.9"
  - "7.1"
sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  - NODE_ENV='test'
script:
  - cp env.example.js env.js
  - npm run lint
  - npm test
  - npm run bundle:ios
matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode8.2
      node_js: false
      before_install:
        - nvm install 7
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn
      xcode_project: comm_admins/ble/ios/RNBluetoothLE.xcodeproj
      xcode_scheme: comm_admins/ble/ios/RNBluetoothLETests
      script:
        - cd ios
        - xcodebuild -scheme RNBluetoothLE -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
        - travis_retry xctool run-tests -scheme RNBluetoothLE -sdk iphonesimulator -launch-timeout 90  ONLY_ACTIVE_ARCH=NO
